export const SET_JOIN_FEEDBACK_GROUP_ID = 'SET_JOIN_FEEDBACK_GROUP_ID';
export const SET_JOIN_FEEDBACK_GROUP_PASSWORD = 'SET_JOIN_FEEDBACK_GROUP_PASSWORD';
export const JOIN_FEEDBACK_GROUP = 'JOIN_FEEDBACK_GROUP';
export const JOIN_FEEDBACK_GROUP_ERROR = 'JOIN_FEEDBACK_GROUP_ERROR';
export const JOIN_FEEDBACK_GROUP_SUCCESS = 'JOIN_FEEDBACK_GROUP_SUCCESS';

export const CREATE_FEEDBACK_GROUP = 'CREATE_FEEDBACK_GROUP';
export const SET_CREATE_FEEDBACK_GROUP_PASSWORD = 'SET_CREATE_FEEDBACK_GROUP_PASSWORD';
