export const FIND_ANONYMOUS_FEEDBACK_GROUP = 'FIND_ANONYMOUS_FEEDBACK_GROUP';
export const FIND_ANONYMOUS_FEEDBACK_GROUP_ERROR = 'FIND_ANONYMOUS_FEEDBACK_GROUP_ERROR';
export const FIND_ANONYMOUS_FEEDBACK_GROUP_SUCCESS = 'FIND_ANONYMOUS_FEEDBACK_GROUP_SUCCESS';

export const FIND_MASTER_FEEDBACK_GROUP = 'FIND_MASTER_FEEDBACK';
export const FIND_MASTER_FEEDBACK_ERROR = 'FIND_MASTER_FEEDBACK_ERROR';
export const FIND_MASTER_FEEDBACK_SUCCESS = 'FIND_MASTER_FEEDBACK_SUCCESS';

export const CREATE_FEEDBACK_GROUP = 'CREATE_FEEDBACK_GROUP';
export const CREATE_FEEDBACK_GROUP_SUCCESS = 'CREATE_FEEDBACK_GROUP_SUCCESS';
export const CREATE_FEEDBACK_GROUP_ERROR = 'CREATE_FEEDBACK_GROUP_ERROR';
